services:
  redis:
    image: redis:7-alpine
    volumes:
      - redis:/data
    ports:
      - 6379:6379
    environment:
      REDIS_ARGS: "--save 60 1"

  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTRES_DB=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

volumes:
  redis:
  postgres: